{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  {{ if .Values.enableAntiAffinity }}
  affinity:
    # ensure nginx won't be on the same node as elasticsearch
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - elasticsearch
        topologyKey: "kubernetes.io/hostname"
  {{ end }}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        # this is plain nginx alpine with embedded fonts
        # all nginx configurations are done using the configmap
        image: orihoch/budgetkey-nginx@sha256:04db7f5b12c5cf486f5e314a6a7da4d9c05dac0bb534d773dcff1e949c863341
        ports:
        - containerPort: 80
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: configmap
          mountPath: /etc/nginx/default_server.conf
          subPath: default_server.conf
        - name: configmap
          mountPath: /etc/nginx/servers.conf
          subPath: servers.conf
        - name: configmap
          mountPath: /etc/nginx/conf.d/kibana.conf
          subPath: kibana.conf
        - name: configmap
          mountPath: /etc/nginx/kibana.htpasswd
          subPath: kibana.htpasswd
        - name: configmap
          mountPath: /etc/nginx/server-rules.conf
          subPath: server-rules.conf
      volumes:
      - name: configmap
        configMap:
          name: nginx
{{ end }}
