apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: travis-ci-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: travis-ci-operator
    spec:
      initContainers:
      - name: permissions
        image: alpine
        command: [sh, -c, "chown -R 1023:1023 /etc/travis-ci-operator && ls -lah /etc/travis-ci-operator"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: etc
          mountPath: /etc/travis-ci-operator
      containers:
      - name: travis-ci-operator
        image: uumpa/travis-ci-operator
        resources: {"requests": {"cpu": "15m", "memory": "50Mi"}, "limits": {"memory": "200Mi"}}
        command: ["bash", "-c", "while true; do sleep 86400; done"]
        volumeMounts:
        - name: etc
          mountPath: /etc/travis-ci-operator
      volumes:
      - name: etc
        {{ if .Values.gcePersistentDiskName }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
        {{ else }}
        emptyDir: {}
        {{ end }}
