apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-search-ui-nginx
data:
  default.conf: |
    server {
      listen 8000;

      auth_basic "Restricted Content";
      auth_basic_user_file /etc/nginx/htpasswd/secret-nginx-htpasswd;

      location /data/ {
        index null;
        root /;
        autoindex on;
      }

      location /search/ {
        proxy_pass http://localhost:5000;
      }

      location /download/ {
        proxy_pass http://localhost:5000;
      }

      location / {
        proxy_pass http://localhost:3000;
      }
    }
